import mysql.connector
mydb = mysql.connector.connect(host='localhost', password='crk@44457778', user='root')
mycursor=mydb.cursor()
mycursor.execute('create database quiz')
mycursor.execute('use quiz')
mycursor.execute('create table ans_key(Code varchar(5) primary key, Answer varchar(30))')

mycursor.execute('create table politics(Code varchar(5), Question varchar(150), Option1 varchar(30), Option2 varchar(30), Option3 varchar(30), Option4 varchar(30),foreign key (Code) references ans_key(Code))')

mycursor.execute("create table science(Code varchar(5), Question varchar(150), Option1 varchar(30), Option2 varchar(30), Option3 varchar(30), Option4 varchar(30), foreign key (Code) references ans_key(Code))")

mycursor.execute("create table superhero(Code varchar(5), Question varchar(150), Option1 varchar(30), Option2 varchar(30), Option3 varchar(30), Option4 varchar(30), foreign key (Code) references ans_key(Code))")

mycursor.execute("create table sports(Code varchar(5), Question varchar(150), Option1 varchar(30), Option2 varchar(30), Option3 varchar(30), Option4 varchar(30), foreign key (Code) references ans_key(Code))")

mycursor.execute("create table mythology(Code varchar(5), Question varchar(150), Option1 varchar(30), Option2 varchar(30), Option3 varchar(30), Option4 varchar(30), foreign key (Code) references ans_key(Code))")


mycursor.execute("insert into ans_key values('po1', 'Dhananjaya Y.C.'),('po2', 'Nirmala sitharaman'),('po3', 'Madras high court'),('po4', '1951'),('po5', 'Raj Narain'),('po6','Vice President of India'),('po7','Pawan Kumar Chamling'),('po8','Nagaland'),('po9','25'),('po10','Kerala')")
mycursor.execute("insert into ans_key values('sc1','Mycology'),('sc2','32'),('sc3','33'),('sc4','Sputnik 1'),('sc5','Travelling'),('sc6','Kelvin'),('sc7','Starch'),('sc8','Octopus'),('sc9','Platypus'),('sc10','Terrestrial Radiation')")
mycursor.execute("insert into ans_key values('sp1','Laeeb'),('sp2','Jagdeep Dhankhar'),('sp3','Max Verstappen'),('sp4','Novak Djokovic'),('sp5','Phrygian cap'),('sp6','George Russell'),('sp7','10'),('sp8','Mary Kom'),('sp9','Jay Shah'),('sp10','Sam Curran')")
mycursor.execute("insert into ans_key values('sh1','Captain America'),('sh2','White'),('sh3','The Avengers'),('sh4','Jean Grey'),('sh5','The Phantom'),('sh6','Avengers:Endgame'),('sh7','Lex Luthor'),('sh8','Vincent Prince'),('sh9','Italy'),('sh10','Batman')")
mycursor.execute("insert into ans_key values('myt1','Hanuman'),('myt2','Jambavan'),('myt3','Sugreeva'),('myt4','North'),('myt5','Rajasuya Yaga'),('myt6','8'),('myt7','Arjuna'),('myt8','Kali'),('myt9','21'),('myt10','Vrika')")


mycursor.execute("insert into politics values('po1','Who is the current cheif justice of India?','Dhananjaya Y.C.','Ranjan Gogoi','Dipak Mishra','Udesh Umesh Lalit'),('po2','Who is minister of finance and corporate affairs?','Rajanath Singh','Nirmala Sitharaman','Narayan Tatu Rane','Sarbanada Sonowal'),('po3','The second largest judicial complex in the world is: ','Guahati High Court','Delhi High Court','Madras high court','Bombay High Court'), ('po4','When was the first general election held in India?','1950','1951','1952','1955'),('po5','The only person who defeated Indira Gandhi in Lok Sabha election 1977','Ram Manohar Lohia','Morarji Desai','Lal Bahadur Shastri','Raj Narain'),('po6','The president of India address his resignation leeter to the: ','Speaker','Vice President of India','Cheif Justice','Prime Minister'),('po7','Who is the longest serving cheif minster of India?','M Karunanidhi','Jyoti Basu','Pawan Kumar Chamling','Manik Sarkar'),('po8','Which state has no Panchayati Raj Institution?','Mizoram','Manipur','Nagaland','Jharkhand'),('po9','Minimum age required to contest for Lok Sabha election is: ','30','35','28','25'), ('po10','Which High cort for the first time in India declared Bandh as illegal?','Allahabad','Gujarat','Kerala','Rajasthan')")

mycursor.execute("insert into science values('sc1','What is the study of mushrooms called','Entomology','Mycology','Cytology','Ornithology'),('sc2','How many teeth does an adult human have?','33','32','34','31'),('sc3','How many vertebrae does the average human possess?','32','33','31','34'),('sc4','What was the name of first manmade satellite launched by the Soviet Union in 1957?','Explorer 1','Kosmos 60','Sputnik 1','Mir'),('sc5','Hodophobia is a fear associated with which of the following?','Sleeping','Walking','Travelling','Running'),('sc6','Which among the following scale is based upon absolute zero?','Celsius','Fahrenheit','Kelvin','Rankine'),('sc7','Cereals are a rich source of which of the following?','Starch','Maltose','Glucose','Fructose'),('sc8','What is the common name of a devilfish?','Loligo','Sepia','Teredo','Octopus'),('sc9','Which of the following is not viviparous?','Mole','Platypus','Kangaroo','Shrew'),('sc10','Even after sunset, air near earths surface continue to receive heat due to:','Insolation','Terrestrial Radiation','Conduction','Convection')")

mycursor.execute("insert into sports values('sp1','What is the name of the official mascot of Qatar World Cup 2022?','Zakumi','Striker','Phuleko','Laeeb'),('sp2','Who represented India at the inaugural FIFA World Cup 2022 in Qatar?','Narendra Modi','Rajanath Singh','Amit Shah','Jagdeep Dhankhar'),('sp3','Who won the F1 Abu Dhabi race that started in Abu Dhabi, United Arab Emirates? ','Max Verstappen','Charles Leclerc','Sergio Perez','Sebastian Vettel'),('sp4','Who is the winner of the 2022 ATP Finals Singles Title?','Novak Djokovic','Rafael Nadal','Casper Rudd','Carlos Alcaraz'),('sp5','Who has been unveiled as the mascot for the 2024 Paris Olympics?','Aubie The Tiger','Sebastian','Phrygian cap','Bucky Badger'),('sp6','Who won the Brazilian Formula One Grand Prix (GP) 2022? ','Lewis Hamilton','George Russell','Max Verstappenc','Sergio Perez'),('sp7','How many sportspersons were elected as members of the Indian Olympic Association (IOA) Athletes Commission?','30','15','10','12'),('sp8',' Who has been elected as the Chairperson of Athletes Commission of the Indian Olympic Association?','Achanta Sharath Kamal','Mirabai Chanu','PV Sindhu','Mary Kom'),('sp9','Who has been elected as the head of ICCs all-powerful Finance and Commercial Affairs (F&CA) committee?','Saurav Ganguly','Wasim Khan','Imran Khwaja','Jay Shah'),('sp10','Who has been named ICC Mens T20 World Cup 2022 Player of the Tournament?','Sam Curran','Virat Kohli','Jos Butler','Suryakumar Yadav')")

mycursor.execute("insert into superhero values('sh1','Which superhero was created by Joe Simon and Jack Kirby','aquaman','Superman','Captain America','Scarlet Witch'),('sh2','What colour of kryptonite is not harmful to superman?','Red','Blue','Green','White'),('sh3','Which films post credit scene did Thanos first appear in?','The Avengers','The Guardians of the Galaxy','Iron man','Doctor Strange'),('sh4','Which character is resurrected in X-men: The Last Stand','Scott','Jean Grey','Professor Xavier','Wolverine'),('sh5','Who was the first superhero ever?','The Phantom','Human Torch','Superman','Bat man'),('sh6','What is the one Marvel film that doesnt have a post-credit scene?','Avengers:Endgame','Avengers','Captain America:civil war','Spiderman No way home'),('sh7','In the DC universe who has higher IQ than Batman?','Lex Luthor','Joker','Cyborg','Wonder woman'),('sh8','Which of the following is not one of Green Lanterns names?','Hal Jordan','Alan Scott','Vincent Prince','Kyle Rayner'),('sh9','The Teenage Mutant Ninja Turtles all have names taken from famous figures in which country?','Russia','France','Italy','England'),('sh10','Which Superhero was not created by comic book legend Stan Lee?','Iron man','Spiderman','Batman','The X-Men')")

mycursor.execute("insert into mythology values('myt1','Who delivered the message of victory of Rama over Ravana to Sita?','Neela','Hanuman','Jambavan','Angada'),('myt2','.From among the following, whom did Rama trust enough to give his ring before his departure to search for Sita?','Hanuman','Jambavan','Angada','Neela'),('myt3','.Which of the following tempted Hanuman making him to open his chest with his Nails?','Nala','Angada','Sugreeva','Rama'),('myt4','In which of the following directions did Hanuman fly to bring Mrithyu Sanjeevini?','East','North', 'North West','North East'),('myt5','Which of the following yagas did Krishna persuade Dharmaraya to Conduct?','Rajasuya yaga','Digvijaya yaga','Vishwashanthi yaga','Puthra kameshti yaga'),('myt6','How many Siddhis did Hanuman Possess?','5','6','8','4'),('myt7','Among the following who is called Madhyama Pandava?','Bheema','Arjuna','Nakula','Sahadeva'),('myt8','In Mythology which Goddess always keeps her tongue fully stretched out?','Durga','Lakshmi','Saraswathi','Kali'),('myt9','How many times did Parasurama go round the earth killing kshathriyas?','9','12','21','15'),('myt10','Among the following who got from shiva the boon of reducing any body whom he touched into ashes?','Tarakasura','Vrika','Nishumbha','Akampana')")

mydb.commit()
mydb.close()
